version: "3.9"

services:

  # mongo_db:
  #   container_name: mongoContainer
  #   image: mongo:latest
  #   restart: on-failure
  #   volumes:
  #     - mongo_db://data/db
  #   ports:
  #     - 27017:27017

  api:
    build: './server/'
    container_name: api
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      MONGODB_URI: mongodb+srv://mongo:mongo@cluster0.bfwwyxa.mongodb.net/mission-6
    # depends_on:
    #   - mongo_db

  client:
    build: './client/'
    container_name: client
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - api

# volumes:
#   mongo_db: {}
